const books = [
  {
    title: "Basic English Grammar",
    author: "Betty Schrampfer Azar",
    publisher: "Pearson Education",
    level: "Beginner",
    ageGroup: "6-12",
    publication: "2019-01-15",
    price: 29.99,
    id: 0,
    rate: 4.5,
  },
  {
    title: "English for Academic Purposes",
    author: "Edward de Chazal",
    publisher: "Cambridge University Press",
    level: "Intermediate",
    ageGroup: "13-18",
    publication: "2020-03-22",
    price: 34.99,
    id: 1,
    rate: 9.0,
  },
  {
    title: "Advanced English Grammar",
    author: "Martin Hewings",
    publisher: "Cambridge University Press",
    level: "Advanced",
    ageGroup: "22+",
    publication: "2018-05-30",
    price: 39.99,
    id: 2,
    rate: 8.0,
  },
  {
    title: "English Vocabulary Builder",
    author: "Merriam-Webster",
    publisher: "Merriam-Webster, Inc.",
    level: "Intermediate",
    ageGroup: "10-18",
    publication: "2021-08-12",
    price: 24.99,
    id: 3,
    rate: 3.5,
  },
  {
    title: "Writing Skills in English",
    author: "John Langan",
    publisher: "McGraw-Hill Education",
    level: "Intermediate",
    ageGroup: "13-18",
    publication: "2022-07-19",
    price: 32.99,
    id: 4,
    rate: 8.7,
  },
  {
    title: "English for Specific Purposes",
    author: "Alison P. Williams",
    publisher: "Cambridge University Press",
    level: "Advanced",
    ageGroup: "22+",
    publication: "2021-11-04",
    price: 37.99,
    id: 5,
    rate: 4.2,
  },
  {
    title: "Practical English Usage",
    author: "Michael Swan",
    publisher: "Oxford University Press",
    level: "Intermediate",
    ageGroup: "13-18",
    publication: "2016-05-12",
    price: 28.99,
    id: 6,
    rate: 8.3,
  },
  {
    title: "English Grammar for Dummies",
    author: "Leslie C. S. C. M. C.",
    publisher: "Wiley Publishing, Inc.",
    level: "Beginner",
    ageGroup: "10-16",
    publication: "2019-09-10",
    price: 19.99,
    id: 7,
    rate: 1.0,
  },
  {
    title: "Communicating in English for Beginners",
    author: "Ruth Gairns & Stuart Redman",
    publisher: "Cambridge University Press",
    level: "Beginner",
    ageGroup: "6-12",
    publication: "2020-02-25",
    price: 22.99,
    id: 8,
    rate: 2.1,
  },
  {
    title: "English Literature for Young Readers",
    author: "Various Authors",
    publisher: "Scholastic Inc.",
    level: "Intermediate",
    ageGroup: "10-15",
    publication: "2021-04-15",
    price: 25.99,
    id: 9,
    rate: 8.4,
  },
  {
    title: "English Idioms in Use",
    author: "Michael McCarthy & Felicity O'Dell",
    publisher: "Cambridge University Press",
    level: "Intermediate",
    ageGroup: "15+",
    publication: "2017-03-01",
    price: 29.99,
    id: 10,
    rate: 4.5,
  },
  {
    title: "Essential Grammar in Use",
    author: "Raymond Murphy",
    publisher: "Cambridge University Press",
    level: "Beginner",
    ageGroup: "10+",
    publication: "2019-06-15",
    price: 29.99,
    id: 11,
    rate: 9.2,
  },
  {
    title: "The Elements of Style",
    author: "William Strunk Jr. & E.B. White",
    publisher: "Pearson Education",
    level: "Advanced",
    ageGroup: "18+",
    publication: "2018-10-01",
    price: 15.99,
    id: 12,
    rate: 9.5,
  },
  {
    title: "The Joy of Vocabulary!",
    author: "Eileen Wordsmith",
    publisher: "Lexicon Books",
    level: "Intermediate",
    ageGroup: "12+",
    publication: "2020-09-15",
    price: 22.5,
    id: 13,
    rate: 5.0,
  },
  {
    title: "Mastering English Grammar",
    author: "Samantha Smithson",
    publisher: "Language Learning Press",
    level: "Advanced",
    ageGroup: "18+",
    publication: "2021-05-20",
    price: 34.99,
    id: 14,
    rate: 6.8,
  },
  {
    title: "Reading Comprehension Success in 20 Minutes a Day",
    author: "LearningExpress Editors",
    publisher: "LearningExpress, LLC.",
    level: "Intermediate",
    ageGroup: "12+",
    publication: "2019-11-01",
    price: 19.95,
    id: 15,
    rate: 3.0,
  },

]

export default books
